package com.hyx.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pro_catalog
 */
public class ProCatalog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_catalog.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_catalog.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_catalog.create_at
     *
     * @mbg.generated
     */
    private Long createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_catalog.update_at
     *
     * @mbg.generated
     */
    private Long updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_catalog.id
     *
     * @return the value of pro_catalog.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_catalog.id
     *
     * @param id the value for pro_catalog.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_catalog.name
     *
     * @return the value of pro_catalog.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_catalog.name
     *
     * @param name the value for pro_catalog.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_catalog.create_at
     *
     * @return the value of pro_catalog.create_at
     *
     * @mbg.generated
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_catalog.create_at
     *
     * @param createAt the value for pro_catalog.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_catalog.update_at
     *
     * @return the value of pro_catalog.update_at
     *
     * @mbg.generated
     */
    public Long getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_catalog.update_at
     *
     * @param updateAt the value for pro_catalog.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Long updateAt) {
        this.updateAt = updateAt;
    }
}