package com.hyx.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table profession
 */
public class Profession implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.img
     *
     * @mbg.generated
     */
    private String img;

    /**
     * Database Column Remarks:
     *   职业名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   职业方向
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.dvp_direction
     *
     * @mbg.generated
     */
    private String dvpDirection;

    /**
     * Database Column Remarks:
     *   门槛
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.limit_condition
     *
     * @mbg.generated
     */
    private Integer limitCondition;

    /**
     * Database Column Remarks:
     *   困难
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.difficulty
     *
     * @mbg.generated
     */
    private Integer difficulty;

    /**
     * Database Column Remarks:
     *   成长周期始
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.periodOne
     *
     * @mbg.generated
     */
    private Integer periodone;

    /**
     * Database Column Remarks:
     *   成长周期末
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.periodTwo
     *
     * @mbg.generated
     */
    private Integer periodtwo;

    /**
     * Database Column Remarks:
     *   稀缺程度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.carrer_prospects
     *
     * @mbg.generated
     */
    private Integer carrerProspects;

    /**
     * Database Column Remarks:
     *   工资始
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.salaryOne
     *
     * @mbg.generated
     */
    private Integer salaryone;

    /**
     * Database Column Remarks:
     *   工资末
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.salaryTwo
     *
     * @mbg.generated
     */
    private Integer salarytwo;

    /**
     *   在学人数
     * @mbg.generated
     */
    private Integer stuCount;

    /**
     * @mbg.generated
     */
    private Long createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.update_at
     *
     * @mbg.generated
     */
    private Long updateAt;

    /**
     * Database Column Remarks:
     *   职业简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.intro
     *
     * @mbg.generated
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.id
     *
     * @return the value of profession.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.id
     *
     * @param id the value for profession.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.img
     *
     * @return the value of profession.img
     *
     * @mbg.generated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.img
     *
     * @param img the value for profession.img
     *
     * @mbg.generated
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.name
     *
     * @return the value of profession.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.name
     *
     * @param name the value for profession.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.dvp_direction
     *
     * @return the value of profession.dvp_direction
     *
     * @mbg.generated
     */
    public String getDvpDirection() {
        return dvpDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.dvp_direction
     *
     * @param dvpDirection the value for profession.dvp_direction
     *
     * @mbg.generated
     */
    public void setDvpDirection(String dvpDirection) {
        this.dvpDirection = dvpDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.limit_condition
     *
     * @return the value of profession.limit_condition
     *
     * @mbg.generated
     */
    public Integer getLimitCondition() {
        return limitCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.limit_condition
     *
     * @param limitCondition the value for profession.limit_condition
     *
     * @mbg.generated
     */
    public void setLimitCondition(Integer limitCondition) {
        this.limitCondition = limitCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.difficulty
     *
     * @return the value of profession.difficulty
     *
     * @mbg.generated
     */
    public Integer getDifficulty() {
        return difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.difficulty
     *
     * @param difficulty the value for profession.difficulty
     *
     * @mbg.generated
     */
    public void setDifficulty(Integer difficulty) {
        this.difficulty = difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.periodOne
     *
     * @return the value of profession.periodOne
     *
     * @mbg.generated
     */
    public Integer getPeriodone() {
        return periodone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.periodOne
     *
     * @param periodone the value for profession.periodOne
     *
     * @mbg.generated
     */
    public void setPeriodone(Integer periodone) {
        this.periodone = periodone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.periodTwo
     *
     * @return the value of profession.periodTwo
     *
     * @mbg.generated
     */
    public Integer getPeriodtwo() {
        return periodtwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.periodTwo
     *
     * @param periodtwo the value for profession.periodTwo
     *
     * @mbg.generated
     */
    public void setPeriodtwo(Integer periodtwo) {
        this.periodtwo = periodtwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.carrer_prospects
     *
     * @return the value of profession.carrer_prospects
     *
     * @mbg.generated
     */
    public Integer getCarrerProspects() {
        return carrerProspects;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.carrer_prospects
     *
     * @param carrerProspects the value for profession.carrer_prospects
     *
     * @mbg.generated
     */
    public void setCarrerProspects(Integer carrerProspects) {
        this.carrerProspects = carrerProspects;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.salaryOne
     *
     * @return the value of profession.salaryOne
     *
     * @mbg.generated
     */
    public Integer getSalaryone() {
        return salaryone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.salaryOne
     *
     * @param salaryone the value for profession.salaryOne
     *
     * @mbg.generated
     */
    public void setSalaryone(Integer salaryone) {
        this.salaryone = salaryone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.salaryTwo
     *
     * @return the value of profession.salaryTwo
     *
     * @mbg.generated
     */
    public Integer getSalarytwo() {
        return salarytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.salaryTwo
     *
     * @param salarytwo the value for profession.salaryTwo
     *
     * @mbg.generated
     */
    public void setSalarytwo(Integer salarytwo) {
        this.salarytwo = salarytwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.stu_count
     *
     * @return the value of profession.stu_count
     *
     * @mbg.generated
     */
    public Integer getStuCount() {
        return stuCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.stu_count
     *
     * @param stuCount the value for profession.stu_count
     *
     * @mbg.generated
     */
    public void setStuCount(Integer stuCount) {
        this.stuCount = stuCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.create_at
     *
     * @return the value of profession.create_at
     *
     * @mbg.generated
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.create_at
     *
     * @param createAt the value for profession.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.update_at
     *
     * @return the value of profession.update_at
     *
     * @mbg.generated
     */
    public Long getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.update_at
     *
     * @param updateAt the value for profession.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Long updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.intro
     *
     * @return the value of profession.intro
     *
     * @mbg.generated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.intro
     *
     * @param intro the value for profession.intro
     *
     * @mbg.generated
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    @Override
    public String toString() {
        return "Profession{" +
                "id=" + id +
                ", img='" + img + '\'' +
                ", name='" + name + '\'' +
                ", dvpDirection='" + dvpDirection + '\'' +
                ", limitCondition=" + limitCondition +
                ", difficulty=" + difficulty +
                ", periodone=" + periodone +
                ", periodtwo=" + periodtwo +
                ", carrerProspects=" + carrerProspects +
                ", salaryone=" + salaryone +
                ", salarytwo=" + salarytwo +
                ", stuCount=" + stuCount +
                ", createAt=" + createAt +
                ", updateAt=" + updateAt +
                ", intro='" + intro + '\'' +
                '}';
    }
}